name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito

    steps:
      - name: List files
        run: echo $GITHUB_OUTPUT

  second-job:
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola segundo mundo ${{ github.ref }}"
