name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Generate a file
        run: |
          echo "This is a test file" >> test.log

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.log
