name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Generate a file
        run: |
          echo "This is a test file" >> test.log

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.log

  second_job:
    runs-on: ubuntu-latest

    needs: first_job

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-artifact

      - name: Display artifact content
        run: |
          cat test.log
