name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: [Hello, World, from, GitHub, Actions]

    steps:
      - name: Print message
        run: echo "${{ matrix.message }}"
